ALTER TABLE "Your Profile" ADD COLUMN IF NOT EXISTS seller_action TEXT DEFAULT NULL;
ALTER TABLE "Your Profile" ADD COLUMN IF NOT EXISTS seller_action_at TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE "Your Profile" ADD COLUMN IF NOT EXISTS refund_initiated BOOLEAN DEFAULT FALSE;

ALTER TABLE sellers ADD COLUMN IF NOT EXISTS penalty_pending BOOLEAN DEFAULT FALSE;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS penalty_amount NUMERIC DEFAULT 0;

ALTER TABLE withdrawal_requests ADD COLUMN IF NOT EXISTS penalty_deduction NUMERIC DEFAULT 0;
ALTER TABLE withdrawal_requests ADD COLUMN IF NOT EXISTS penalty_order_id TEXT DEFAULT NULL;
